# Generated by Django 4.2.15 on 2026-09-22 07:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0004_invoice_sales_order_invoiceitem_sales_order_item_and_more'),
        ('product', '0005_alter_product_current_stock_and_more'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('return_number', models.CharField(blank=True, max_length=50)),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(choices=[('damaged_product', 'Damaged Product'), ('wrong_item', 'Wrong Item'), ('quality_issue', 'Quality Issue'), ('other', 'Other')], default='wrong_item', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refunded', 'Refunded'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('invoice_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('already_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('eligible_to_return', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('return_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('applied_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('from_company_name', models.CharField(blank=True, default='TUNGSTON LABS', max_length=255)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=100)),
                ('finance_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='customer.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='invoice.invoice')),
            ],
            options={
                'db_table': 'finance_sales_return',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoiced_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('already_returned_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('returning_now_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('return_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_items', to='invoice.invoiceitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_items', to='product.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_return.salesreturn')),
            ],
            options={
                'db_table': 'finance_sales_return_item',
            },
        ),
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('company', 'return_number'), name='unique_sales_return_number_per_company'),
        ),
    ]
