# Generated by Django 4.2.15 on 2026-09-17 04:50

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_product_sub_category'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cn_number', models.CharField(blank=True, max_length=50)),
                ('invoice_ref', models.CharField(blank=True, default='', max_length=100)),
                ('issue_date', models.DateField()),
                ('reason', models.CharField(choices=[('sales_return', 'Sales Return'), ('price_adjustment', 'Price Adjustment'), ('damaged_goods', 'Damaged Goods'), ('discount_adjustment', 'Discount Adjustment'), ('pricing_error', 'Pricing Error'), ('other', 'Other')], default='sales_return', max_length=50)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_applied', 'Partially Applied'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('draft', 'Draft')], default='open', max_length=50)),
                ('from_company_name', models.CharField(blank=True, default='Tungston Labs', max_length=200)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='customer.customer')),
            ],
            options={
                'db_table': 'finance_credit_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='credit_note.creditnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='product.product')),
            ],
            options={
                'db_table': 'finance_credit_note_item',
            },
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('company', 'cn_number'), name='unique_cn_number_per_company'),
        ),
    ]
