# Generated by Django 4.2.15 on 2026-09-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_sales_order_invoiceitem_sales_order_item_and_more'),
        ('credit_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoice.invoice'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='invoice.invoiceitem'),
        ),
    ]
