# Generated by Django 4.2.15 on 2026-09-29 10:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('product', '0005_alter_product_current_stock_and_more'),
        ('bill', '0001_initial'),
        ('vendor', '0002_alter_vendorpayment_options_vendorpayment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dn_number', models.CharField(blank=True, max_length=50)),
                ('bill_ref', models.CharField(blank=True, default='', max_length=150)),
                ('issue_date', models.DateField()),
                ('reason', models.CharField(choices=[('returned_goods', 'Returned Goods'), ('damaged_goods', 'Damaged Goods'), ('defective_items', 'Defective Items'), ('overbilling', 'Overbilling'), ('quality_issue', 'Quality Issue'), ('wrong_item_delivered', 'Wrong Item Delivered'), ('pricing_error', 'Pricing Error'), ('other', 'Other')], default='damaged_goods', max_length=50)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_applied', 'Partially Applied'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('draft', 'Draft')], default='open', max_length=50)),
                ('from_company_name', models.CharField(blank=True, default='Tungston Labs', max_length=250)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_to_name', models.CharField(blank=True, default='', max_length=250)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('bill_to_phone', models.CharField(blank=True, default='', max_length=50)),
                ('finance_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_notes', to='bill.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='vendor.vendor')),
            ],
            options={
                'db_table': 'finance_debit_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, default='', max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('billed_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('already_debited_qty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_items', to='bill.billitem')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='debit_note.debitnote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_items', to='product.product')),
            ],
            options={
                'db_table': 'finance_debit_note_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='debitnote',
            constraint=models.UniqueConstraint(fields=('company', 'dn_number'), name='unique_debit_note_number_per_company'),
        ),
    ]
