# Generated by Django 4.2.15 on 2026-09-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('warehouse', '0003_alter_warehouse_manager'),
        ('product', '0004_product_sub_category'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dn_number', models.CharField(blank=True, max_length=50)),
                ('so_ref', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_date', models.DateField()),
                ('delivery_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('partially_delivered', 'Partially Delivered'), ('partial', 'Partial'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='delivered', max_length=50)),
                ('invoice_status', models.CharField(choices=[('not_invoiced', 'Not Invoiced'), ('partially_invoiced', 'Partially Invoiced'), ('fully_invoiced', 'Fully Invoiced')], default='not_invoiced', max_length=50)),
                ('from_company_name', models.CharField(blank=True, default='Tungston Labs', max_length=200)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('contact_person', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='customer.customer')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'finance_delivery_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('hs_code', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_note.deliverynote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_items', to='product.product')),
            ],
            options={
                'db_table': 'finance_delivery_note_item',
            },
        ),
        migrations.AddConstraint(
            model_name='deliverynote',
            constraint=models.UniqueConstraint(fields=('company', 'dn_number'), name='unique_dn_number_per_company'),
        ),
    ]
