# Generated by Django 4.2.15 on 2026-09-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0001_initial'),
        ('delivery_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='sales_order.salesorder'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_items', to='sales_order.salesorderitem'),
        ),
    ]
