# Generated by Django 4.2.15 on 2026-09-09 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_reserved_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_alter_warehouse_code'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('current_available_qty', models.IntegerField(default=0)),
                ('adjustment_type', models.CharField(choices=[('addition', 'Addition (+)'), ('subtraction', 'Subtraction (-)')], default='addition', max_length=20)),
                ('adjustment_quantity', models.IntegerField(default=1)),
                ('reason', models.CharField(blank=True, default='correction', max_length=150)),
                ('reference_document', models.CharField(blank=True, default='', max_length=150)),
                ('adjustment_date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='product.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'finance_stock_adjustment',
                'ordering': ['-created_at'],
            },
        ),
    ]
