# Generated by Django 4.2.15 on 2026-09-09 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='adjusted_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='stock_adjustments/'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('addition', 'Addition (+)'), ('subtraction', 'Subtraction (-)'), ('add_stock', 'Add Stock'), ('reduce_stock', 'Reduce Stock')], default='addition', max_length=20),
        ),
    ]
