# Generated by Django 4.2.15 on 2026-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockadjustment_adjusted_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('add_stock', 'Add Stock'), ('reduce_stock', 'Reduce Stock'), ('remove_stock', 'Remove Stock'), ('set_exact_quantity', 'Set Exact Quantity'), ('addition', 'Addition (+)'), ('subtraction', 'Subtraction (-)'), ('Add Stock', 'Add Stock'), ('Reduce Stock', 'Reduce Stock'), ('Remove Stock', 'Remove Stock'), ('Set Exact Quantity', 'Set Exact Quantity')], default='add_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(blank=True, default='Damaged Goods', max_length=150),
        ),
    ]
