# Generated by Django 4.2.15 on 2026-09-11 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(choices=[('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('technology', 'Technology'), ('hospitality', 'Hospitality'), ('finance', 'Finance'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('cr_number', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(choices=[('AED', 'AED'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('SAR', 'SAR'), ('QAR', 'QAR'), ('BHD', 'BHD'), ('KWD', 'KWD'), ('OMR', 'OMR')], max_length=10)),
                ('vat_number', models.CharField(blank=True, default='', max_length=100)),
                ('payment_term', models.CharField(choices=[('immediate', 'Immediate'), ('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], default='30_days', max_length=20)),
                ('cr_expiry_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('postal', models.CharField(blank=True, default='', max_length=20)),
                ('phno', models.CharField(blank=True, default='', max_length=30)),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('financial_email', models.EmailField(blank=True, default='', max_length=254)),
                ('technical_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='customer_documents/')),
                ('document_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer.customer')),
            ],
            options={
                'db_table': 'finance_customer_document',
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'customer_id'), name='unique_customer_id_per_company'),
        ),
    ]
