# Generated by Django 4.2.15 on 2026-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trade_license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
