# Generated by Django 4.2.15 on 2026-10-01 04:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchaseorder', '0001_initial'),
        ('vendor', '0002_alter_vendorpayment_options_vendorpayment_created_by_and_more'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('purchase_order', 'Purchase Order'), ('bill', 'Bill'), ('payment', 'Payment'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note'), ('manual', 'Manual Entry')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='vendor/ledger/')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='bill.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ledger_entries', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendor_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='vendor.vendorpayment')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='purchaseorder.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='vendor.vendor')),
            ],
            options={
                'db_table': 'finance_vendor_ledger',
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
