# Generated by Django 4.2.15 on 2026-10-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorledger', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendorledger',
            constraint=models.UniqueConstraint(condition=models.Q(('bill__isnull', False)), fields=('bill',), name='unique_vendor_ledger_bill'),
        ),
        migrations.AddConstraint(
            model_name='vendorledger',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment',), name='unique_vendor_ledger_payment'),
        ),
        migrations.AddConstraint(
            model_name='vendorledger',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_order__isnull', False)), fields=('purchase_order',), name='unique_vendor_ledger_purchase_order'),
        ),
    ]
