# Generated by Django 4.2.15 on 2026-09-23 09:23

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_trade_license_number'),
        ('product', '0005_alter_product_current_stock_and_more'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBilling',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50)),
                ('recurring_type', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill')], default='invoice', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('total_recurrence', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited_recurrence', models.BooleanField(default=False)),
                ('payment_term', models.CharField(choices=[('immediate', 'Due on Receipt'), ('7_days', '7 Days'), ('15_days', '15 Days'), ('30_days', '30 Days'), ('45_days', '45 Days'), ('60_days', '60 Days'), ('90_days', '90 Days')], default='30_days', max_length=20)),
                ('reminder_before_due_days', models.PositiveIntegerField(default=0)),
                ('reminder_before_renewal_days', models.PositiveIntegerField(default=0)),
                ('billing_cycle', models.CharField(choices=[('advance', 'Advance'), ('arrears', 'Arrears')], default='advance', max_length=20)),
                ('auto_email_to', models.EmailField(blank=True, default='', max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('auto_generate_invoice', models.BooleanField(default=False)),
                ('auto_send', models.BooleanField(default=False)),
                ('include_tax', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('recurrence_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('next_invoice_date', models.DateField(blank=True, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_billings', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_billings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_billings', to='customer.customer')),
            ],
            options={
                'db_table': 'finance_recurring_billing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('product_service_name', models.CharField(max_length=200)),
                ('hs_code', models.CharField(blank=True, default='', max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit', models.CharField(choices=[('PCS', 'Piece (PCS)'), ('Box', 'Box'), ('Pack', 'Pack'), ('Month', 'Month'), ('Project', 'Project'), ('Set', 'Set'), ('Kg', 'Kilogram (Kg)'), ('Meter', 'Meter'), ('Other', 'Other')], default='Month', max_length=50)),
                ('billing_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], default='recurring', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('technology', models.CharField(blank=True, default='', max_length=200)),
                ('database', models.CharField(blank=True, default='', max_length=200)),
                ('product_icon', models.ImageField(blank=True, null=True, upload_to='recurring/product_icons/')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='recurring/screenshots/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_services', to='category.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_services', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_services', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_services', to='product.product')),
            ],
            options={
                'db_table': 'finance_recurring_service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPricingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('service_id', models.CharField(blank=True, default='', max_length=100)),
                ('users', models.PositiveIntegerField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recurring_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='recurring.recurringservice')),
            ],
            options={
                'db_table': 'finance_recurring_pricing_plan',
            },
        ),
        migrations.CreateModel(
            name='RecurringBillingOccurrence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurrence_number', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent'), ('paid', 'Paid'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('recurring_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='recurring.recurringbilling')),
            ],
            options={
                'db_table': 'finance_recurring_billing_occurrence',
                'ordering': ['scheduled_date', 'occurrence_number'],
            },
        ),
        migrations.AddField(
            model_name='recurringbilling',
            name='recurring_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_contracts', to='recurring.recurringservice'),
        ),
        migrations.AddConstraint(
            model_name='recurringpricingplan',
            constraint=models.UniqueConstraint(fields=('recurring_service', 'plan_type'), name='unique_recurring_plan_type'),
        ),
        migrations.AddConstraint(
            model_name='recurringbillingoccurrence',
            constraint=models.UniqueConstraint(fields=('recurring_billing', 'occurrence_number'), name='unique_recurring_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='recurringbilling',
            constraint=models.UniqueConstraint(fields=('company', 'contract_number'), name='unique_contract_number_per_company'),
        ),
    ]
