# Generated by Django 4.2.15 on 2026-09-29 09:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0003_alter_warehouse_manager'),
        ('vendor', '0001_initial'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_alter_product_current_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(blank=True, max_length=50)),
                ('pr_reference', models.CharField(blank=True, default='', max_length=100)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('receipt_status', models.CharField(choices=[('pending', 'Pending'), ('partially_received', 'Partially Received'), ('received', 'Received')], default='pending', max_length=30)),
                ('bill_status', models.CharField(choices=[('pending', 'Pending'), ('partially_billed', 'Partially Billed'), ('billed', 'Billed')], default='pending', max_length=30)),
                ('shipping_method', models.CharField(choices=[('road', 'Road'), ('air', 'Air'), ('sea', 'Sea'), ('courier', 'Courier'), ('pickup', 'Pickup'), ('other', 'Other')], default='road', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendor.vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hs_code', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='product.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchaseorder.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'po_number'), name='unique_purchase_order_number_per_company'),
        ),
    ]
