# Generated by Django 4.2.15 on 2026-10-07 11:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('account_code', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, choices=[('current_asset', 'Current Asset'), ('non_current_asset', 'Non-Current Asset'), ('current_liability', 'Current Liability'), ('non_current_liability', 'Non-Current Liability'), ('equity', 'Equity'), ('operating_revenue', 'Operating Revenue'), ('other_revenue', 'Other Revenue'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('other_expense', 'Other Expense')], default='', max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('opening_balance_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chart_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_accounts', to='accounting.chartofaccount')),
            ],
            options={
                'db_table': 'accounting_chart_of_accounts',
                'ordering': ['account_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('company', 'account_code'), name='unique_account_code_per_company'),
        ),
    ]
