# Generated by Django 4.2.15 on 2026-09-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
