# Generated by Django 4.2.15 on 2026-09-28 10:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('product', '0005_alter_product_current_stock_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=100)),
                ('po_reference', models.CharField(blank=True, default='', max_length=150)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_note', models.CharField(blank=True, default='', max_length=150)),
                ('payment_terms', models.CharField(default='NET 10', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone', models.CharField(blank=True, default='', max_length=100)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_to_name', models.CharField(blank=True, default='', max_length=255)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('bill_to_phone', models.CharField(blank=True, default='', max_length=100)),
                ('bill_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('finance_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_bills', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_bills', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_bills', to='vendor.vendor')),
            ],
            options={
                'db_table': 'finance_purchase_bill',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('particular', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hs_code', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vat_sar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.bill')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='product.product')),
            ],
            options={
                'db_table': 'finance_purchase_bill_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('company', 'bill_number'), name='unique_purchase_bill_number_per_company'),
        ),
    ]
