# Generated by Django 4.2.15 on 2026-09-14 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_product_sub_category'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.DateField()),
                ('valid_till', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('from_company_name', models.CharField(blank=True, default='Tungston Labs', max_length=200)),
                ('from_address', models.TextField(blank=True, default='')),
                ('from_phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('bill_to_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_to_address', models.TextField(blank=True, default='')),
                ('bill_to_phone', models.CharField(blank=True, default='', max_length=50)),
                ('finance_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quote_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('negotiation_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='customer.customer')),
            ],
            options={
                'db_table': 'finance_quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('hs_code', models.CharField(blank=True, default='', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='product.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation')),
            ],
            options={
                'db_table': 'finance_quotation_item',
            },
        ),
        migrations.CreateModel(
            name='QuotationConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('partial_payment', 'Partial Payment')], default='full_payment', max_length=50)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('other', 'Other')], default='bank_transfer', max_length=50)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_conversions', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_conversions', to='customer.customer')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='quotation.quotation')),
            ],
            options={
                'db_table': 'finance_quotation_conversion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('company', 'quote_number'), name='unique_quote_number_per_company'),
        ),
    ]
