# Generated by Django 4.2.15 on 2026-09-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('category', '0001_initial'),
        ('warehouse', '0002_alter_warehouse_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(choices=[('PCS', 'Piece (PCS)'), ('Box', 'Box'), ('Pack', 'Pack'), ('Month', 'Month'), ('Project', 'Project'), ('Set', 'Set'), ('Kg', 'Kilogram (Kg)'), ('Meter', 'Meter'), ('Other', 'Other')], default='PCS', max_length=50)),
                ('hsn_sac_code', models.CharField(blank=True, default='', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('opening_stock_qty', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('inclusive', 'Inclusive'), ('exclusive', 'Exclusive'), ('exempt', 'Exempt'), ('none', 'None')], default='vat', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'finance_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_product_code_per_company'),
        ),
    ]
