# Generated by Django 4.2.15 on 2026-09-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_qty',
            field=models.IntegerField(default=0),
        ),
    ]
