# Generated by Django 4.2.15 on 2026-09-21 11:43

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('invoice', '0004_invoice_sales_order_invoiceitem_sales_order_item_and_more'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('opening_balance', 'Opening Balance'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('adjustment', 'Adjustment')], max_length=30)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledger_entries', to='superadmin.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customer.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to='invoice.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to='payment.payment')),
            ],
            options={
                'db_table': 'finance_customer_ledger',
                'ordering': ['transaction_date', 'id'],
                'indexes': [models.Index(fields=['company', 'customer', 'transaction_date'], name='ledger_cust_date_idx'), models.Index(fields=['company', 'transaction_type'], name='ledger_company_type_idx')],
            },
        ),
    ]
