# Generated by Django 4.2.15 on 2026-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoiceitem_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
